name: Alejandro Rituerto Sin
markdown: kramdown

gmail_username:       aleritu
github_username:      arituerto
linkedin_username:    arituerto

collections:
  publications:
    output: true
  projects:
    output: true

gems:
  - jekyll-octicons
